version: "3.8"
services:
  janus-gateway:
    container_name: janus-gateway
    build:
      dockerfile: ./Dockerfile
      context: .
    image: janus-image
    volumes:
      - ./config/:/opt/janus/etc/janus/
      - ./log/:/var/log/
    restart: always
    ports:
      - 7088:7088
      - 8088:8088
      - 8188:8188
      - 10000-10030:10000-10030/udp
  web-server:
    container_name: janus-web-server
    image: httpd:alpine
    restart: always
    ports:
      - 12345:80
    volumes:
      - ./html:/usr/local/apache2/htdocs
